// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Pomnia
/** Auto-generated by scripts/generate-build-info.mjs — do not edit by hand. */
export const BUILD_VERSION = "0.1.45"
export const BUILD_GIT_SHA = "7ff41c7"
export const BUILD_TIMESTAMP = "2026-07-30 01:01"
export const BUILD_DIRTY = true

/** `0.1.44 · 4155ea9 · 2026-07-30 01:12` (dirty → `4155ea9+dirty`). */
export function formatBuildIdentity(
  version = BUILD_VERSION,
  sha = BUILD_GIT_SHA,
  timestamp = BUILD_TIMESTAMP,
  dirty = BUILD_DIRTY,
): string {
  const ref = dirty ? `${sha}+dirty` : sha
  return `${version} · ${ref} · ${timestamp}`
}
